// Likes Worker
// ------------
// A tiny Cloudflare Worker that stores blog-post likes in Workers KV.
// The static site on GitHub Pages calls this Worker over HTTPS.
//
// KV layout (one big flat key-value store, no schema):
//   count:<articleId>              -> total like count (string integer)
//   visitor:<visitorId>:<articleId> -> "1" if that visitor currently likes it (auto-expires after ~400 days)
//   rl:<ip>                         -> per-IP write rate-limit counter (auto-expires)
//   rlr:<ip>                        -> per-IP read rate-limit counter (auto-expires)

// Only these origins are allowed to call the Worker.
// GitHub Pages for prod, localhost for when testing the site locally.
const ALLOWED_ORIGINS = [
  "https://dannybimma.github.io",
  "http://localhost:8000",
  "http://127.0.0.1:8000",
];

// Visitor IDs must look like a standard UUID (generated by crypto.randomUUID()
// on the client). Anything else is rejected so the KV doesn't fill up with junk.
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// Article IDs must be lowercase kebab-case and reasonably short.
// This matches the data-article-id values on the blog (e.g. "ai-is-cocaine").
const ARTICLE_ID_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;

// Rate limit: up to 30 toggle requests per minute from the same IP.
// The KV key expires automatically after the window ends.
const RATE_LIMIT_WINDOW_SECONDS = 60;
const RATE_LIMIT_MAX = 30;

// Separate, much more generous limit for the read path (GET /likes).
// Reads are cheap but still cost KV reads + Worker invocations; 120/min per IP
// is plenty for a real human bouncing around the blog, but stops spam from
// draining free-tier quotas.
const READ_RATE_LIMIT_MAX = 120;

// TTL for `visitor:*:*` keys. ~400 days — matches the browser cookie lifetime
// ballpark, stops KV storage growing forever if an attacker cycles UUIDs.
// A returning visitor who likes again just resets the TTL.
const VISITOR_KEY_TTL_SECONDS = 60 * 60 * 24 * 400;

// Build the CORS headers attached to every response.
// If the caller's origin isn't in the allow-list; still to send *some*
// Access-Control-Allow-Origin, to fall back to the prod origin.
function corsHeaders(origin) {
  const allowed = ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Max-Age": "86400",
    // Tells caches the response varies by Origin so the wrong CORS header
    // doesn't get served to the wrong caller.
    Vary: "Origin",
  };
}

// Small helper to return a JSON response with CORS headers attached.
function json(body, init, origin) {
  return new Response(JSON.stringify(body), {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...corsHeaders(origin),
      ...(init && init.headers),
    },
  });
}

// Simple sliding-window rate limiter keyed by IP.
// Reads the current count, bumps it, and writes it back with a TTL equal to
// the window size. If already at the max, then reject.
// `prefix` keeps separate buckets for reads vs writes (rl: vs rlr:).
async function rateLimit(env, ip, prefix, max) {
  const key = `${prefix}:${ip}`;
  const raw = await env.LIKES.get(key);
  const count = raw ? parseInt(raw, 10) : 0;
  if (count >= max) return false;
  await env.LIKES.put(key, String(count + 1), {
    expirationTtl: RATE_LIMIT_WINDOW_SECONDS,
  });
  return true;
}

// Batch read: for every requested article id, look up its total count and
// whether the calling visitor currently likes it. Returns a plain object keyed
// by article id: { "ai-is-cocaine": { count: 7, liked: true }, ... }.
async function readCounts(env, ids, visitorId) {
  const result = {};
  await Promise.all(
    ids.map(async (id) => {
      const [countRaw, likedRaw] = await Promise.all([
        env.LIKES.get(`count:${id}`),
        // If no visitorId was supplied, skip the "did you like this" check
        // and leave liked=false — the front-end treats that as "not yet liked".
        visitorId ? env.LIKES.get(`visitor:${visitorId}:${id}`) : null,
      ]);
      result[id] = {
        count: countRaw ? parseInt(countRaw, 10) : 0,
        liked: Boolean(likedRaw),
      };
    }),
  );
  return result;
}

// Toggle logic: flips the caller's like state for a given article.
// If they already liked it → remove the visitor key and decrement the count.
// If they hadn't → add the visitor key and increment the count.
// Returns the new state so the client can update its UI without a second fetch.
async function toggleLike(env, articleId, visitorId) {
  const visitorKey = `visitor:${visitorId}:${articleId}`;
  const countKey = `count:${articleId}`;
  const alreadyLiked = Boolean(await env.LIKES.get(visitorKey));
  const currentCount = parseInt((await env.LIKES.get(countKey)) || "0", 10);

  if (alreadyLiked) {
    await env.LIKES.delete(visitorKey);
    // Clamp at zero just in case something ever got out of sync.
    const next = Math.max(0, currentCount - 1);
    await env.LIKES.put(countKey, String(next));
    return { count: next, liked: false };
  }

  // Stamp the visitor key with a TTL so abandoned UUIDs don't live forever in
  // KV. Active visitors re-set the TTL every time they toggle, so real users
  // never lose their like state.
  await env.LIKES.put(visitorKey, "1", { expirationTtl: VISITOR_KEY_TTL_SECONDS });
  const next = currentCount + 1;
  await env.LIKES.put(countKey, String(next));
  return { count: next, liked: true };
}

// The Worker entrypoint. Cloudflare calls fetch() for every incoming request.
export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";
    const url = new URL(request.url);

    // CORS preflight — browsers send an OPTIONS before cross-origin POSTs.
    // Just echo the allow headers back, no body needed.
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders(origin) });
    }

    // Cloudflare puts the real client IP in this header. Fall back to a
    // forwarded-for header or "unknown" so rate limiting still has something
    // to key on even in weird setups.
    const ip =
      request.headers.get("CF-Connecting-IP") ||
      request.headers.get("X-Forwarded-For") ||
      "unknown";

    // --- GET /likes?ids=a,b,c&visitorId=<uuid> -------------------------------
    // Batch endpoint the page hits once on load to paint all like counts.
    if (request.method === "GET" && url.pathname === "/likes") {
      // Generous per-IP read limit. Real visitors hit this once per page load;
      // a spammer trying to burn our KV read + Worker invocation quotas gets
      // cut off at 120/min per IP.
      if (!(await rateLimit(env, ip, "rlr", READ_RATE_LIMIT_MAX))) {
        return json({ error: "rate limited" }, { status: 429 }, origin);
      }
      const idsParam = url.searchParams.get("ids") || "";
      const visitorId = url.searchParams.get("visitorId") || "";
      // Split the comma list, validate each id against the regex, cap at 50
      // so an attacker can't ask for a million keys in one request.
      const ids = idsParam
        .split(",")
        .map((s) => s.trim())
        .filter((s) => ARTICLE_ID_RE.test(s))
        .slice(0, 50);
      if (ids.length === 0) {
        return json({ error: "no valid ids" }, { status: 400 }, origin);
      }
      // visitorId is optional on GET — if it's missing/garbage, just don't
      // populate the "liked" flag.
      const vid = UUID_RE.test(visitorId) ? visitorId : "";
      const counts = await readCounts(env, ids, vid);
      return json(counts, { status: 200 }, origin);
    }

    // --- POST /likes/:articleId ---------------------------------------------
    // Toggle endpoint. Body must be {"visitorId":"<uuid>"}.
    if (request.method === "POST" && url.pathname.startsWith("/likes/")) {
      const articleId = decodeURIComponent(url.pathname.slice("/likes/".length));
      if (!ARTICLE_ID_RE.test(articleId)) {
        return json({ error: "invalid article id" }, { status: 400 }, origin);
      }
      let body;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid json" }, { status: 400 }, origin);
      }
      const visitorId = (body && body.visitorId) || "";
      if (!UUID_RE.test(visitorId)) {
        return json({ error: "invalid visitor id" }, { status: 400 }, origin);
      }
      // Tighter per-IP write limit — writes cost more KV quota and get abused
      // faster. Real users clicking like buttons never get close to 30/min.
      if (!(await rateLimit(env, ip, "rl", RATE_LIMIT_MAX))) {
        return json({ error: "rate limited" }, { status: 429 }, origin);
      }
      const result = await toggleLike(env, articleId, visitorId);
      return json(result, { status: 200 }, origin);
    }

    // Anything else is a 404.
    return json({ error: "not found" }, { status: 404 }, origin);
  },
};
